# This file derived from template located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.11-slim

services:
  - redis:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

test:
  script:
    - apt-get update -y
    - apt-get install git -y
    - apt-get install build-essential -y
    - pip install .
    - pip install coverage mypy
    - sleep 5
    # - apt-get install redis -y
    - apt-get install redis-server -y
    - redis-cli -h redis ping
    - cd /builds/LiRI/projects/lcpvian
    - mypy lcpvian
    - python setup.py build_ext --inplace
    # unit tests will not work until db access exists
    # - coverage run -m unittest
    # - coverage report
